import fs from "node:fs";
const src = fs.readFileSync(new URL("../src/App.jsx", import.meta.url), "utf8");
const a = src.indexOf("/* =========================================================================\n   TRAINING");
const b = src.indexOf("/* ---------------- geluid, trilling");
const wma = src.slice(src.indexOf("function weekMapAdjusted"), src.indexOf("/* Aandeel van de gewichtstoename"));
const pre = wma + `const num=(v,f)=>{const n=Number(v);return Number.isFinite(n)?n:f;};const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));const sum=(a)=>a.reduce((x,y)=>x+y,0);const DAY_MS=86400000;const dayNum=(iso)=>Math.round(Date.parse(iso+"T00:00:00")/DAY_MS);const useState=()=>{};const useEffect=()=>{};`;
const L = new Function(pre + src.slice(a, b) + "return {busyAlternatives, buildExIndex};")();
const idx = L.buildExIndex([], {});
let fails = 0; const ok = (l, c, i = "") => { if (!c) fails++; console.log((c ? "OK  " : "FOUT") + " " + l + (i ? "  → " + i : "")); };
const show = (r) => r.map((o) => `${o.ex.name} (${o.why.join("; ")})`).join(" | ");
let r = L.busyAlternatives(idx.chest_press, idx, [], new Set(["chest_press", "bankdrukken"]));
ok("chest press bezet: 3 borst-compounds, geen machine eerst, bankdrukken niet (zit al in training)", r.length === 3 && r.every((o) => o.ex.pri[0] === "borst" && o.ex.kind === "compound") && r[0].ex.equip !== "machine" && !r.some((o) => o.ex.id === "bankdrukken"), show(r));
r = L.busyAlternatives(idx.pec_deck, idx, [], new Set(["pec_deck"]));
ok("pec deck bezet: isolatie voor borst", r[0].ex.kind === "isolation" && r[0].ex.pri[0] === "borst", show(r));
r = L.busyAlternatives(idx.lat_pulldown, idx, [], new Set(["lat_pulldown"]));
ok("lat pulldown bezet: eerst verticaal trekken", r[0].ex.pri[0] === "rug" && ["pulldown_1arm","optrekken"].includes(r[0].ex.id), show(r));
r = L.busyAlternatives(idx.squat, idx, [], new Set(["squat"]));
ok("squat bezet: kniebuiging (geen deadlift)", ["front_squat","hack_squat","leg_press","bulgarian_split_squat","walking_lunge"].includes(r[0].ex.id), show(r));
const sessions = [{ end: 1, date: "2026-09-20", exercises: [{ exId: "smith_schuin", sets: [{ type: "work", done: true, weight: 50, reps: 8 }, { type: "work", done: true, weight: 52.5, reps: 7 }] }] }];
r = L.busyAlternatives(idx.chest_press, idx, sessions, new Set(["chest_press"]));
const sm = r.find((o) => o.ex.id === "smith_schuin");
ok("eerder gedane oefening krijgt voorrang en toont vorige prestatie", sm && sm.why.some((w) => /52,5 kg × 7/.test(w)), show(r));
console.log(fails ? `${fails} FOUT` : "Alle tests geslaagd"); process.exit(fails ? 1 : 0);
