import fs from "node:fs";
const src = fs.readFileSync(new URL("../src/App.jsx", import.meta.url), "utf8");
const a = src.indexOf("const BULK_BLOCK_WEEKS"); const b = src.indexOf("function calorieCorrection");
const L = new Function(`const DAY_MS=86400000;const dayNum=(iso)=>Math.round(Date.parse(iso+"T00:00:00")/DAY_MS);` + src.slice(a, b) + "return {phaseLengthAdvice};")();
let fails = 0;
const eq = (l, g, e) => { const ok = JSON.stringify(g) === JSON.stringify(e); if (!ok) fails++; console.log((ok ? "OK  " : "FOUT") + " " + l + (ok ? "" : `  kreeg ${JSON.stringify(g)} verwacht ${JSON.stringify(e)}`)); };
const t = "2026-09-28";
const k = (x) => (x ? [x.kind, x.weeks, x.pause ?? x.from] : null);
eq("cut 9 wk: niets", k(L.phaseLengthAdvice({ goal: "cut", since: { goal: "cut", date: "2026-07-27" }, today: t })), null);
eq("cut 10 wk: pauze 3", k(L.phaseLengthAdvice({ goal: "cut", since: { goal: "cut", date: "2026-07-20" }, today: t })), ["pauze", 10, 3]);
eq("cut eigen instelling 12/2", k(L.phaseLengthAdvice({ goal: "cut", since: { goal: "cut", date: "2026-07-20" }, today: t, cutWeeks: 12, cutPause: 2 })), null);
eq("bulk 15 wk: niets", k(L.phaseLengthAdvice({ goal: "bulk", since: { goal: "bulk", date: "2026-06-15" }, today: "2026-09-27" })), null);
eq("bulk 16 wk: pauze 4", k(L.phaseLengthAdvice({ goal: "bulk", since: { goal: "bulk", date: "2026-06-08" }, today: t })), ["pauze", 16, 4]);
eq("onderhoud zonder pauze: niets", k(L.phaseLengthAdvice({ goal: "onderhoud", since: { goal: "onderhoud", date: "2026-01-01" }, today: t })), null);
const brk = { from: "cut", rate: -0.5, weeks: 3 };
eq("pauze 2 wk: niets", k(L.phaseLengthAdvice({ goal: "onderhoud", since: { goal: "onderhoud", date: "2026-09-14" }, brk, today: t })), null);
eq("pauze 3 wk: hervatten", k(L.phaseLengthAdvice({ goal: "onderhoud", since: { goal: "onderhoud", date: "2026-09-07" }, brk, today: t })), ["hervatten", 3, "cut"]);
eq("na plan telt vanaf einde plan", k(L.phaseLengthAdvice({ goal: "cut", since: { goal: "cut", date: "2026-01-01" }, from: "2026-09-01", today: t })), null);
eq("oude datum, ander doel: niets", k(L.phaseLengthAdvice({ goal: "cut", since: { goal: "bulk", date: "2026-01-01" }, today: t })), null);
const x = L.phaseLengthAdvice({ goal: "cut", since: { goal: "cut", date: "2026-07-20" }, today: t });
eq("uitgesteld", L.phaseLengthAdvice({ goal: "cut", since: { goal: "cut", date: "2026-07-20" }, today: t, snooze: { key: x.key, until: "2026-10-05" } }), null);
eq("uitstel verlopen", !!L.phaseLengthAdvice({ goal: "cut", since: { goal: "cut", date: "2026-07-20" }, today: "2026-10-05", snooze: { key: x.key, until: "2026-10-05" } }), true);
console.log(fails ? `${fails} FOUT` : "Alle tests geslaagd"); process.exit(fails ? 1 : 0);
