import fs from "node:fs";
const src = fs.readFileSync(new URL("../src/App.jsx", import.meta.url), "utf8");
const a = src.indexOf("/* =========================================================================\n   TRAINING");
const b = src.indexOf("/* ---------------- geluid, trilling");
const wma = src.slice(src.indexOf("function weekMapAdjusted"), src.indexOf("/* Aandeel van de gewichtstoename"));
const pre = wma + `const num=(v,f)=>{const n=Number(v);return Number.isFinite(n)?n:f;};const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));const sum=(a)=>a.reduce((x,y)=>x+y,0);const DAY_MS=86400000;const dayNum=(iso)=>Math.round(Date.parse(iso+"T00:00:00")/DAY_MS);const useState=()=>{};const useEffect=()=>{};`;
const L = new Function(pre + src.slice(a, b) + `return {buildExIndex,trainDerive,TRAIN_DEFAULT,programFromTemplate,TEMPLATES,phaseOptions,plannedSetsFor};`)();
let fails = 0;
const eq = (l, g, e) => { const ok = JSON.stringify(g) === JSON.stringify(e); if (!ok) fails++; console.log((ok ? "OK  " : "FOUT") + " " + l + (ok ? "" : `  kreeg ${JSON.stringify(g)} verwacht ${JSON.stringify(e)}`)); };
const ids = (p, prev) => L.phaseOptions(p, prev).map((o) => o.id);
eq("bulk", ids("bulk"), ["gelijk"]);
eq("cut", ids("cut"), ["gelijk", "minder"]);
eq("slotcut", ids("slotcut"), ["minder", "gelijk"]);
eq("minicut", ids("minicut"), ["minicut", "gelijk"]);
eq("onderhoud na cut", ids("onderhoud", "cut"), ["herstel", "gelijk"]);
eq("onderhoud na minicut", ids("onderhoud", "minicut"), ["herstel", "gelijk"]);
eq("onderhoud zonder voorgaande", ids("onderhoud"), ["gelijk", "herstel"]);
const T0 = L.TRAIN_DEFAULT();
const tpl = L.TEMPLATES[0];
const prog = L.programFromTemplate(tpl, { mode: "week", sets: 2, exIndex: L.buildExIndex([], {}) });
const T = { ...T0, programs: [prog], activeProgramId: prog.id };
const d = (t, phase) => L.trainDerive(t, { phase, adjList: [] }, "2026-09-28");
// bestaande gebruiker, nog niets gezien
eq("nieuw, cut: niet vragen", [d(T, "cut").phasePending, d(T, "cut").phaseOn], [false, false]);
eq("nieuw, minicut: wel vragen, nog gelijk", [d(T, "minicut").phasePending, d(T, "minicut").phaseOn], [true, false]);
const Tc = { ...T, phaseSeen: "cut" };
eq("cut -> minicut: vragen", d(Tc, "minicut").phasePending, true);
eq("cut -> cut: niet vragen", d(Tc, "cut").phasePending, false);
const Tm = { ...Tc, phaseChoice: { phase: "minicut", option: "minicut" }, phaseSeen: "minicut", phasePrev: "cut" };
const Dm = d(Tm, "minicut");
eq("minicut gekozen", [Dm.phasePending, Dm.phaseOn, Dm.tp.load, Math.round(Dm.tp.vf * 100)], [false, true, false, 67]);
const day = prog.days[0];
console.log("   sets", day.name, L.plannedSetsFor(day, { ...d(Tc, "cut"), pos: { phase: "opbouw" } }).join(","), "->", L.plannedSetsFor(day, { ...Dm, pos: { phase: "opbouw" } }).join(","));
const Tg = { ...Tm, phaseChoice: { phase: "minicut", option: "gelijk" } };
eq("minicut, blijven", [d(Tg, "minicut").phaseOn, d(Tg, "minicut").tp.load], [false, true]);
eq("minicut -> onderhoud: vragen, herstel", [d(Tm, "onderhoud").phasePending, d(Tm, "onderhoud").tp.options[0].id], [true, "herstel"]);
eq("oude keuze geldt niet in nieuwe fase", d(Tm, "onderhoud").phaseOn, false);
eq("automatische stand: aanbevolen alvast actief", d({ ...Tc, settings: { ...Tc.settings, autoProgress: true } }, "slotcut").tp.option.id, "minder");
eq("oude akkoordknop minicut", d({ ...Tc, phaseAccept: "minicut" }, "minicut").tp.option.id, "minicut");
console.log(fails ? `${fails} FOUT` : "Alle tests geslaagd");
process.exit(fails ? 1 : 0);
